date:
  year: 2024
  month: 6
  day: 2
  hour: 12
  minute: 0
  second: 0

time:
  fsim: 1000 # [Hz]
  frcvr: 50 # [Hz]
  fimu: 100 # [Hz]

errors:
  ionosphere: klobuchar
  troposphere: saastamoinen
  rx_clock: high_quality_tcxo

imu:
  osr: 1
  mobility: [1.0, 10.0, 60.0]
  model: consumer

constellations:
  mask_angle: 7.5 # [deg]
  emitters:
    gps:
      signal: gps
      
mc_params:
  scenarios: ["static", "dynamic"]
  # attenuation: [0, 5, 10, 15, 20, 22.5, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 37.5, 40]
  attenuation: [0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 35.0, 40.0]
  imu_models: ["consumer", "industrial", "tactical"]
  n_ant: [1, 2, 3, 4]
  n_runs: 100
  init_pva_err_std: [3.0, 3.0, 5.0, 0.1, 0.1, 0.15, 3.0, 3.0, 10.0] # m, m/s, deg