date:
  year: 2024
  month: 6
  day: 2
  hour: 12
  minute: 0
  second: 0

time:
  fsim: 1000 # [Hz]
  frcvr: 50 # [Hz]
  fimu: 100 # [Hz]

errors:
  ionosphere: klobuchar
  troposphere: saastamoinen
  rx_clock: high_quality_tcxo

imu:
  osr: 1
  mobility: [1.0, 10.0, 60.0]
  model: consumer

constellations:
  mask_angle: 7.5 # [deg]
  emitters:
    gps:
      signal: gps
      
mc_params:
  # scenarios: ["static", "dynamic"]
  scenarios: ["dynamic"]
  attenuation: [15.0, 17.5, 20.0, 22.0, 24.0, 26.0, 28.0, 30.0, 32.0, 34.0, 37.0, 40.0]
  # attenuation: [0.0]
  imu_models: ["consumer"]
  # imu_models: ["tactical"]
  n_ant: [1,2,3,4]
  # n_ant: [1]
  n_runs: 30
  init_pva_err_std: [1.0, 1.0, 2.0, 0.05, 0.05, 0.1, 0.5, 0.5, 2.0] # m, m/s, deg