date:
  year: 2024
  month: 5
  day: 2
  hour: 12
  minute: 0
  second: 0

time:
  duration: 204.499
  # duration: 4.999
  fsim: 1000 # [Hz]
  frcvr: 50 # [Hz]
  fimu: 100 # [Hz]

errors:
  ionosphere: klobuchar
  troposphere: saastamoinen
  rx_clock: high_quality_tcxo

imu:
  model: consumer
  osr: 1
  mobility: [3.0, 1.5, 6.0]

constellations:
  mask_angle: 7.5 # [deg]
  emitters:
    gps:
      signal: gps
      js: [0.0, 5.0, 10.0, 15.0, 20.0, 24.0, 26.0, 28.0, 30.0, 32.0, 34.0, 36.0, 40.0, 45.0]