time:
  # duration: 204.49
  # duration: 1800.0
  duration: 15
  fsim: 1 # [Hz]
  year: 2024
  month: 1
  day: 1
  hour: 12
  minute: 0
  second: 0

constellations:
  mask_angle: 5.0 # [deg]
  emitters:
    # iridium-next:
    #   signal: iridium
    # orbcomm:
    #   signal: orbcomm
    buoy:
      signal: buoy

errors:
  # ionosphere: klobuchar
  # troposphere: saastamoinen
  rx_clock: ocxo

imu:
  model: hg1700
  osr: 10
  mobility: [3.0, 1.5, 6.0]
  # vibration_model: sinusoidal